// export/docx.js -- minimal, dependency-free .docx (OOXML) generation,
// ported from Wisprflow's src/Main/Docx.fs: a .docx is a ZIP of a few XML
// parts, built by hand (STORED entries + CRC32) so no zip library is
// needed. Word opens the result normally.
import { triggerDownload } from "./download.js";
import { toTurns, speakerCount, fmtClock } from "../shared.js";

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(bytes) {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) crc = CRC_TABLE[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function u16(n) {
  const b = new Uint8Array(2);
  new DataView(b.buffer).setUint16(0, n & 0xffff, true);
  return b;
}
function u32(n) {
  const b = new Uint8Array(4);
  new DataView(b.buffer).setUint32(0, n >>> 0, true);
  return b;
}
function concatBytes(chunks) {
  const total = chunks.reduce((n, c) => n + c.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const c of chunks) {
    out.set(c, off);
    off += c.length;
  }
  return out;
}

/// Build a ZIP archive (all entries STORED/uncompressed) from {name, data}
/// objects where data is a Uint8Array.
function zipStored(entries) {
  const parts = [];
  const central = [];
  let offset = 0;
  for (const e of entries) {
    const name = new TextEncoder().encode(e.name);
    const data = e.data;
    const crc = crc32(data);
    const local = concatBytes([
      u32(0x04034b50), u16(20), u16(0), u16(0), u16(0), u16(0),
      u32(crc), u32(data.length), u32(data.length), u16(name.length), u16(0), name,
    ]);
    parts.push(local, data);
    const cent = concatBytes([
      u32(0x02014b50), u16(20), u16(20), u16(0), u16(0), u16(0), u16(0),
      u32(crc), u32(data.length), u32(data.length), u16(name.length), u16(0), u16(0), u16(0), u16(0),
      u32(0), u32(offset), name,
    ]);
    central.push(cent);
    offset += local.length + data.length;
  }
  const cd = concatBytes(central);
  const end = concatBytes([
    u32(0x06054b50), u16(0), u16(0), u16(entries.length), u16(entries.length),
    u32(cd.length), u32(offset), u16(0),
  ]);
  return concatBytes([...parts, cd, end]);
}

function xmlEsc(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

const contentTypesXml =
  '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
  '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' +
  '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' +
  '<Default Extension="xml" ContentType="application/xml"/>' +
  '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>' +
  "</Types>";

const relsXml =
  '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
  '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
  '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>' +
  "</Relationships>";

function para(bold, rest) {
  const boldRun = bold ? `<w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">${xmlEsc(bold)}</w:t></w:r>` : "";
  const restRun = rest ? `<w:r><w:t xml:space="preserve">${xmlEsc(rest)}</w:t></w:r>` : "";
  return `<w:p>${boldRun}${restRun}</w:p>`;
}

function heading(text) {
  return `<w:p><w:r><w:rPr><w:b/><w:sz w:val="32"/></w:rPr><w:t xml:space="preserve">${xmlEsc(text)}</w:t></w:r></w:p>`;
}

export function buildDocx(title, rows) {
  const turns = toTurns(rows);
  const body =
    heading(title) +
    para("", `${speakerCount(rows)} speakers · ${rows.length} segments · generated by transcribr-web`) +
    para("", "") +
    turns.map((r) => para(`${r.speaker_id} [${fmtClock(r.timestamp_start)}–${fmtClock(r.timestamp_end)}]  `, r.transcribed_text)).join("");
  const documentXml =
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
    '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' +
    "<w:body>" + body + "<w:sectPr/></w:body></w:document>";
  const enc = new TextEncoder();
  return zipStored([
    { name: "[Content_Types].xml", data: enc.encode(contentTypesXml) },
    { name: "_rels/.rels", data: enc.encode(relsXml) },
    { name: "word/document.xml", data: enc.encode(documentXml) },
  ]);
}

export function downloadDocx(title, rows, filename) {
  triggerDownload(
    new Blob([buildDocx(title, rows)], { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" }),
    filename
  );
}
